// Code generated by stanc v2.38.0
#include <stan/model/model_header.hpp>
namespace survival_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 22> locations_array__ =
  {" (found before start of program)",
  " (in 'engine_package/models/survival.stan', line 12, column 2 to column 18)",
  " (in 'engine_package/models/survival.stan', line 13, column 2 to column 16)",
  " (in 'engine_package/models/survival.stan', line 29, column 2 to column 36)",
  " (in 'engine_package/models/survival.stan', line 17, column 2 to column 25)",
  " (in 'engine_package/models/survival.stan', line 18, column 2 to column 28)",
  " (in 'engine_package/models/survival.stan', line 21, column 4 to line 24, column 6)",
  " (in 'engine_package/models/survival.stan', line 20, column 17 to line 25, column 3)",
  " (in 'engine_package/models/survival.stan', line 20, column 2 to line 25, column 3)",
  " (in 'engine_package/models/survival.stan', line 2, column 2 to column 17)",
  " (in 'engine_package/models/survival.stan', line 3, column 2 to column 17)",
  " (in 'engine_package/models/survival.stan', line 4, column 8 to column 9)",
  " (in 'engine_package/models/survival.stan', line 4, column 2 to column 39)",
  " (in 'engine_package/models/survival.stan', line 5, column 8 to column 9)",
  " (in 'engine_package/models/survival.stan', line 5, column 2 to column 42)",
  " (in 'engine_package/models/survival.stan', line 6, column 8 to column 9)",
  " (in 'engine_package/models/survival.stan', line 6, column 2 to column 37)",
  " (in 'engine_package/models/survival.stan', line 7, column 18 to column 19)",
  " (in 'engine_package/models/survival.stan', line 7, column 2 to column 30)",
  " (in 'engine_package/models/survival.stan', line 8, column 18 to column 19)",
  " (in 'engine_package/models/survival.stan', line 8, column 2 to column 29)",
  " (in 'engine_package/models/survival.stan', line 12, column 9 to column 10)"};
class survival_model final : public model_base_crtp<survival_model> {
 private:
  int N;
  int J;
  std::vector<int> event;
  std::vector<int> interval;
  std::vector<int> trt;
  Eigen::Matrix<double,-1,1> exposure_data__;
  Eigen::Matrix<double,-1,1> weights_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> exposure{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> weights{nullptr, 0};
 public:
  ~survival_model() {}
  survival_model(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "survival_model_namespace::survival_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 9;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 9;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 10;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 10;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 11;
      stan::math::validate_non_negative_index("event", "N", N);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "event", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      event = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 12;
      event = context__.vals_i("event");
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "event", event, 0);
      current_statement__ = 12;
      stan::math::check_less_or_equal(function__, "event", event, 1);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("interval", "N", N);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "interval", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      interval = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 14;
      interval = context__.vals_i("interval");
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "interval", interval, 1);
      current_statement__ = 14;
      stan::math::check_less_or_equal(function__, "interval", interval, J);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("trt", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "trt", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      trt = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 16;
      trt = context__.vals_i("trt");
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "trt", trt, 0);
      current_statement__ = 16;
      stan::math::check_less_or_equal(function__, "trt", trt, 1);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("exposure", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "exposure", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      exposure_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                          std::numeric_limits<double>::quiet_NaN());
      new (&exposure)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(exposure_data__.data(), N);
      {
        std::vector<local_scalar_t__> exposure_flat__;
        current_statement__ = 18;
        exposure_flat__ = context__.vals_r("exposure");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(exposure, exposure_flat__[(pos__ - 1)],
            "assigning variable exposure", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "exposure", exposure, 0);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("weights", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "weights", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      weights_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                         std::numeric_limits<double>::quiet_NaN());
      new (&weights)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(weights_data__.data(), N);
      {
        std::vector<local_scalar_t__> weights_flat__;
        current_statement__ = 20;
        weights_flat__ = context__.vals_r("weights");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(weights, weights_flat__[(pos__ - 1)],
            "assigning variable weights", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "weights", weights, 0);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("alpha", "J", J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = J + 1;
  }
  inline std::string model_name() const final {
    return "survival_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.38.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "survival_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 2;
      auto beta_trt = in__.template read<local_scalar_t__>();
      {
        current_statement__ = 4;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha,
                         static_cast<double>(0), 2.5));
        current_statement__ = 5;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_trt,
                         static_cast<double>(0), 2.5));
        current_statement__ = 8;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 6;
          lp_accum__.add((stan::model::rvalue(weights, "weights",
                            stan::model::index_uni(i)) *
            stan::math::poisson_log_lpmf<false>(
              stan::model::rvalue(event, "event", stan::model::index_uni(i)),
              ((stan::math::log(
                  stan::model::rvalue(exposure, "exposure",
                    stan::model::index_uni(i))) +
              stan::model::rvalue(alpha, "alpha",
                stan::model::index_uni(
                  stan::model::rvalue(interval, "interval",
                    stan::model::index_uni(i))))) + (beta_trt *
              stan::model::rvalue(trt, "trt", stan::model::index_uni(i)))))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "survival_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 2;
      auto beta_trt = in__.template read<local_scalar_t__>();
      {
        current_statement__ = 4;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(alpha,
                         static_cast<double>(0), 2.5));
        current_statement__ = 5;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_trt,
                         static_cast<double>(0), 2.5));
        current_statement__ = 8;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 6;
          lp_accum__.add((stan::model::rvalue(weights, "weights",
                            stan::model::index_uni(i)) *
            stan::math::poisson_log_lpmf<false>(
              stan::model::rvalue(event, "event", stan::model::index_uni(i)),
              ((stan::math::log(
                  stan::model::rvalue(exposure, "exposure",
                    stan::model::index_uni(i))) +
              stan::model::rvalue(alpha, "alpha",
                stan::model::index_uni(
                  stan::model::rvalue(interval, "interval",
                    stan::model::index_uni(i))))) + (beta_trt *
              stan::model::rvalue(trt, "trt", stan::model::index_uni(i)))))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "survival_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 2;
      auto beta_trt = in__.template read<local_scalar_t__>();
      out__.write(alpha);
      out__.write(beta_trt);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double hazard_ratio = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      hazard_ratio = stan::math::exp(beta_trt);
      out__.write(hazard_ratio);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable alpha");
      out__.write(alpha);
      local_scalar_t__ beta_trt = DUMMY_VAR__;
      current_statement__ = 2;
      beta_trt = in__.read<local_scalar_t__>();
      out__.write(beta_trt);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_trt",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 1;
        alpha_flat__ = context__.vals_r("alpha");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(alpha);
      local_scalar_t__ beta_trt = DUMMY_VAR__;
      current_statement__ = 2;
      beta_trt = context__.vals_r("beta_trt")[(1 - 1)];
      out__.write(beta_trt);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "beta_trt"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"hazard_ratio"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(J)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta_trt");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "hazard_ratio");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "beta_trt");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "hazard_ratio");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta_trt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"hazard_ratio\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"beta_trt\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"hazard_ratio\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = J + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = J + 1;
    const size_t num_transformed = emit_transformed_parameters * (0U);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = survival_model_namespace::survival_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return survival_model_namespace::profiles__;
}
#endif